# --- DOSYA: bot_token.py (v13) ---
TELEGRAM_TOKEN = "7661702671:AAHZ3H1qedEY3_B9idt0yaYnJybe65W5Vv0"

# BU DOSYADAN ADMİN LİSTESİNİ KALDIRDIK. HER ŞEY DİNAMİK.
# SADECE SENİN İLK ADMIN OLMAN İÇİN ID'Nİ BURADA TUTUYORUZ.
# İLK ADMIN KEY'İNİ GİRDİKTEN SONRA BURAYLA İŞİN KALMIYOR.
ADMIN_ID = 7272527047 # BURAYA SADECE KENDİ TELEGRAM ID'Nİ YAZ
